### ISSUE TITLE
Terminal quits when called with `-h` or `--help` flags.

### ISSUE THREAD

**Issue by psetq** [elementary/terminal#314] opened 2018-10-29 16:51 UTC
When I attempt to launch the terminal with the -h or --help flags the terminal quits.

For example, I launch the terminal with `SUPR-T`, then in the terminal application I type 

    io.elementary.terminal --help

The terminal application where I typed that last command closes.

The `--version` flag for the terminal app doesn't seem to return a version.

    ~$ io.elementary.terminal --version
    [DEBUG 09:47:22.006980] Settings.vala:163: Loading settings from schema 'io.elementary.terminal.saved-state'
    [DEBUG 09:47:22.007614] Settings.vala:163: Loading settings from schema 'io.elementary.terminal.settings'

I'm using elementary OS 5.0 Juno.

**Comment by Thalexander** [comment] 2018-10-30 13:31
The help issue is a duplicate of #205.

**Comment by arshubham** [comment] 2018-10-30 13:36
Also duplicate for https://github.com/elementary/terminal/issues/282

**Closed** 2018-11-02 16:33 UTC
Labels: Status: Duplicate
