### ISSUE TITLE
Singleton

### ISSUE THREAD

**Issue by tecty** [elementary/terminal#321] opened 2018-11-09 17:01 UTC
I am using Yakuake previously, I like the Singleton of that app. Could we add a command line argument like gnome-shell, which we can tweak to let it only open one window of this app. When trying to open a new one, I will directly see the old instance.

**Comment by danrabbit** [comment] 2019-12-11 00:46
Closing as a duplicate of #53

**Closed by danrabbit** 2019-12-11 00:46 UTC
