### ISSUE TITLE
Green check is confusing

### ISSUE THREAD

**Issue by snowparrot** [elementary/terminal#316] opened 2018-11-01 20:23 UTC
After a command has been executed and there is no return code "0" Terminal shows an "green check" icon in the tabs.

It is confusing because some popular applications like ssh use more error codes than 0. (e.g. ssh uses 255 for not successful connection)

There should be a less confusing icon.

**Comment by cassidyjames** [comment] 2018-11-01 20:31
According to https://github.com/elementary/terminal/pull/168/files it should show an error icon when the exit status is non-zero.

**Comment by finetuned89** [comment] 2018-12-08 08:49
Trying this with a python script results in the correct icons showing for me:

```python
# exitcode.py
import time
from sys import argv
time.sleep(2)
quit(int(argv[1]))
```

Running `python3 exitcode.py 255` shows a red exclamation mark icon, while `python3 exitcode.py 0` shows the green check mark.

Running `ssh test@ntoheuntoehu.tld` and quickly switching to the next tab after hitting return also shows the red exclamation mark icon, and retrieving the exit code using `echo $?` returns `255`.

Are you running the command as part of a larger script? Because in that case, the return code of the last line in your script will determine the icon:

```shell
# exitcode.sh
sleep 1;
ssh test@thaohdethaoed.tld
echo "Done"
```

Running `. ./exitcode.sh` now results in the green checkmark due to the last line being successful. If ran without the last line, there is a red exclamation mark icon.

**Comment by danrabbit** [comment] 2019-12-11 00:47
Closing because this seems to be working as intended

**Closed by danrabbit** 2019-12-11 00:47 UTC
Labels: Status: Incomplete
