### ISSUE TITLE
Text in terminal is duplicated while resizing it

### ISSUE THREAD

**Issue by pierrers-design** [elementary/terminal#605] opened 2021-07-04 11:41 UTC
## What Happened

The text with the name of the user and the computer before the :~$ in the terminal is duplicated when the size of the window is reduced under the size of the text described before.

Before:
![Capture d’écran de 2021-07-04 13-25-51](https://user-images.githubusercontent.com/74794864/124383413-9c616600-dccc-11eb-9ea8-2c5c70164ae2.png)

While:
![Capture d’écran de 2021-07-04 13-26-09](https://user-images.githubusercontent.com/74794864/124383429-a8e5be80-dccc-11eb-9ddd-4c4aa0d04715.png)

After:
![Capture d’écran de 2021-07-04 13-26-21](https://user-images.githubusercontent.com/74794864/124383436-b26f2680-dccc-11eb-88ed-96a306eae9f3.png)

## Expected Behavior

The text in the terminal should not be duplicated.

## Steps to Reproduce

1. Open the terminal app
2. Reduce it's size to compress the text line before :~$
3. The text is now duplicated

## Platform Information

![Captures d'écran de 2021-07-04 13 37 48](https://user-images.githubusercontent.com/74794864/124383496-0a0d9200-dccd-11eb-82b7-77560b260940.png)

**Comment by jeremypw** [comment] 2021-07-04 17:19
This looks like a duplicate of #407, which is thought to be an upstream issue as Terminal code has nothing to do with text layout withing the terminal widget used.

**Closed by jeremypw** 2021-07-04 17:19 UTC
