### ISSUE TITLE
Terminal tabs should use spinner for active tabs

### ISSUE THREAD

**Issue by hanaral** [elementary/terminal#561] opened 2021-02-22 18:46 UTC
## Problem

There is no way to tell a tab is running a command until it is complete or you attempt to close the app.

## Proposal

Have a spinner like loading tabs in Files has if it is running a command (the macOS terminal does this too)

**Comment by danrabbit** [comment] 2021-02-22 18:56
Closing as a duplicate of #317

**Closed by danrabbit** 2021-02-22 18:56 UTC

**Comment by jeremypw** [comment] 2026-02-23 11:22
No longer completed but not re-opening as duplicate.
