### ISSUE TITLE
Repeated text after change size

### ISSUE THREAD

**Issue by andirsun** [elementary/terminal#549] opened 2020-12-04 22:26 UTC
## Steps to Reproduce

1. Open terminal
2. Do a small resize of app
3. See the glitch

## Platform Information

![deepin-screen-recorder_io elementary terminal_20201204172404](https://user-images.githubusercontent.com/22928302/101221376-9384b500-3655-11eb-85db-d283bc0490f4.gif)

**Comment by jeremypw** [comment] 2020-12-05 12:09
I think this is a duplicate of #407 and is probably down to an upstream issue.

**Closed** 2020-12-06 14:49 UTC
