### ISSUE TITLE
# char in URLs is escaped in a way that breaks the URL

### ISSUE THREAD

**Issue by CodingSpiderFox** [elementary/terminal#704] opened 2023-02-21 19:59 UTC
### What Happened?

Clicked the link `https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt` that was printed and highlighted as link. Browser opened `https://github.com/romkatv/powerlevel10k/blob/master/README.md%23instant-prompt` (note the %23) which is not correct.

### Steps to Reproduce

Open Terminal (v 6.1.1 on elementary 7) 
Execute command `echo "https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt"`
Click the link in the result line

### Expected Behavior

Link opens correctly

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment] 2023-02-22 11:27
Thanks for reporting!  I think this is a duplicate of #625.  Work was started on a PR to fix this (#631) but it ran into difficulties and stalled.  I'll see if it can be completed.

**Comment by jeremypw** [comment] 2023-02-22 12:34
@CodingSpiderFox I have updated #631 so that the example you gave is handled correctly and marked it "Ready for Review".

**Closed** 2023-02-22 12:35 UTC
Labels: Status: Duplicate
