### ISSUE TITLE
Super+T dosen't open new Terminal anymore

### ISSUE THREAD

**Issue by The-Idle-Sloth** [elementary/terminal#440] opened 2020-01-04 08:18 UTC
Hello,

Since the update this morning, my shortcut to open a new terminal doesn't work anymore : the first I open works but once I have 1 teminal openned it doesn't open more terminal.

Regards,
Gregoire

**Comment by The-Idle-Sloth** [comment] 2020-01-04 08:32
Looks like it opens a new tab, not a new window. How do I correct it ?

**Comment by jeremypw** [comment] 2020-01-04 16:57
The behaviour of Terminal launched without any flags was changed to fix other issues reported.  To fix this regression I guess we would have to add another flag `-n` (New Window) which would force another window to be opened.  Would also have to change system shortcuts to use this flag (a custom shortcut could use it in the mean time).

**Comment by queeup** [comment] 2020-01-05 09:56
With `tab-bar-behavior 'Never Show Tabs'` and Super+T also ignore to open new window. It was working before.

**Comment by The-Idle-Sloth** [comment] 2020-01-06 22:27
Thanks for answer, but -n doesn't work for me, it doesn't open any new windows or tab...
I've tried it on command line and in custom shortcut menu but doesn't work for both.

Whatmore, may be update the -h option (and add --help option) so we may know how to fixe little problems like that without posting here ;-)

**Comment by jeremypw** [comment] 2020-01-07 11:35
@The-Idle-Sloth You need to wait until #447 has been merged (and released if you are on the stable version of Hera) before the `-n` flag will work.

**Closed** 2020-01-08 16:32 UTC

**Comment by endorama** [comment] 2020-01-09 22:07
Hello, may I ask when you expect to release this? 

I use multiple workspace and this bug has the side effect of creating a tab in the terminal window opened regardless of the workspace I'm currently in (so ie. if I'm on workspace 3 but terminal is in workspace 1 I have to manually switch to workspace 1). Is very frustrating :) I can live with it, but I'd love an ETA for this to reach Hera. Thanks!

Kudos to the awesome work and this terminal anyway, I'm overall very happy with it!

**Comment by jeremypw** [comment] 2020-01-10 09:26
Unfortunately there has just been a release and normally there is a space of two or three months between releases unless there is a serious issue. If you are on the stable repository you could switch to the daily repository to get fixes as soon as merged but you would have to be aware that this would be more prone to have (temporary) regressions so is not suitable for production use.  There was a regression caused by the recent fix which needs #456 to be merged.

**Comment by kr428** [comment] 2020-01-31 08:21
Any changes or workarounds to that? This is pretty much annoying, even more so as it also affects the "open in terminal" option in the file manager: If there is some terminal open on some virtual desktop, "open in terminal" does at first sight "nothing" (and at second sight open a new tab in this open terminal, so you have to find the window that opened somewhere, yourself...) 😔️

**Comment by jeremypw** [comment] 2020-01-31 17:31
I'll see if I can speed up the next release.

**Comment by jeremypw** [comment] 2020-01-31 17:34
v5.5.1 was release 10 days ago so the `-n` flag should be working in Hera now. So you can use the custom shortcut workround mentioned above in the mean time.

**Comment by kr428** [comment] 2020-02-03 08:47
Ah ok, thanks.
