### ISSUE TITLE
Customization options

### ISSUE THREAD

**Issue by gkdgoutam** [elementary/terminal#522] opened 2020-06-30 09:03 UTC
Hello,

I was wondering if there is any option to customize the terminal. In particular if I want to change the fonts, colors etc. 
I can change in bashrc or something like that, but do you think it is also useful to add `Preferences` with color, font etc.  in settings?

**Comment by jeremypw** [comment] 2020-06-30 17:43
This is a duplicate of #507 and also referenced in #418, so it is under consideration.

**Closed** 2020-06-30 19:33 UTC
Labels: Status: Duplicate
