### ISSUE TITLE
Make the active tab more pronounced.

### ISSUE THREAD

**Issue by Blast-City** [elementary/terminal#506] opened 2020-04-17 17:43 UTC
I usually use Terminal in fullcreen mode and one thing I noticed is that sometimes is difficult to identify which tab is the active one, especially when I have the brightness down

Right now the only way to know that a tab is the active is the black outline on a dark grey background and the x button, but since sometimes the mouse cursor is over a non active tab, it became even more difficult since there are two x's.

What if  the active tab also had an white/light grey line on the bottom of the tab. Firefox does this with a blue line on the top of the active tab and I think it works rather nicely.

Is it just me having this problem?

Sorry if this have been mentioned before and this issue is a duplicate.

Thanks.

**Comment by danrabbit** [comment] 2020-04-17 17:46
Duplicate of https://github.com/elementary/stylesheet/issues/360

**Closed by danrabbit** 2020-04-17 17:46 UTC
Labels: Status: Duplicate
