### ISSUE TITLE
Show the command's success/error in the notification

### ISSUE THREAD

**Issue by megatux** [elementary/terminal#216] opened 2018-03-05 18:29 UTC
Wishlist. Maybe a small green/red icon to know if the result code from the executed command was 0. Is it possible?

**Comment by donadigo** [comment] 2018-03-05 18:31
This is already a thing in master, but I don't think it was released yet. Closing.

**Comment by danrabbit** [comment] 2018-03-05 18:40
AFAICT, notifications only say "Task finished". It doesn't say whether it exited successfully or with an error

**Comment by danrabbit** [comment] 2018-03-22 17:51
Seems like this is a duplicate of #37

**Closed by danrabbit** 2018-03-22 17:51 UTC
Labels: Priority: Wishlist, Status: Duplicate
