### ISSUE TITLE
unreadable text in midnight commander with default color theme

### ISSUE THREAD

**Issue by xevin** [elementary/terminal#313] opened 2018-10-26 10:30 UTC
![screenshot-2018-10-26 15-28-03](https://user-images.githubusercontent.com/5955821/47563790-60cb4700-d93c-11e8-8253-45bdf1f99d10.png)

**Comment by kr428** [comment] 2019-03-27 15:12
Adding myself to this. Used to change this locally by setting a different color scheme in midnight commander itself, but it's not nice to have to do this on multiple servers. Situation:

- Generally, the blue background is too bright and "in your face".
- The default fonts, too, are too bright and hard to read.
- Color for "selected" files is hardly readable on the bright background.
- Color for "selected" files, too, is the same as color used for text files(?) which makes it hard to distinguish "selected" from "unselected" files in larger folders.

Please see screenshot comparing mc in tilix (left) vs. mc in pantheon-terminal (right).

Workaround is playing with the themes in mc, I use "modarcon16root" which at least looks usable but has a few glitches too.

![terminal-2](https://user-images.githubusercontent.com/685879/55087737-dcc3e980-50aa-11e9-91f8-f24a7e35cdba.png)

**Comment by kr428** [comment] 2019-03-29 13:30
Note: This apparently happens, too, for other ncurses based terminal applications such as mutt or screen.

**Comment by cassidyjames** [comment] 2019-10-15 17:51
Duplicate of #39

**Closed by cassidyjames** 2019-10-15 17:51 UTC
