### ISSUE TITLE
Resizing the window duplicates the username text.

### ISSUE THREAD

**Issue by marco4mp** [elementary/terminal#622] opened 2021-09-16 16:39 UTC
## What Happened

Hi! I found this little bug. Resizing the window duplicates the username text.

## Expected Behavior

The text should stay normal.

## Steps to Reproduce

1. Open Terminal
2. Resize the window by dragging the border as little as possible.

https://user-images.githubusercontent.com/52709674/133650082-335a4628-d859-451c-94ac-0b57183c1adb.mp4

### Logs

--

## Platform Information

elementary OS 6 Odin

**Comment by jeremypw** [comment] 2021-09-16 18:26
I think this is a duplicate of #407 (and some others).  It is probably an upstream issue with the vte widget used as Terminal does not do any of the drawing in the terminal.

**Comment by jeremypw** [comment] 2021-09-16 18:32
It might be because the terminal width in chars needs to be explicitly updated when the window width is changed.

**Comment by jeremypw** [comment] 2021-09-19 13:11
After some research I am pretty sure that this is an upstream bug - gnome-terminal also suffers from this.

**Comment by jeremypw** [comment] 2021-09-19 17:35
I have marked this as "Out of scope". I will close it now, but please re-open if you know of a way to fox or work round this in Terminal.

**Closed by jeremypw** 2021-09-19 17:35 UTC
Labels: Status: Out of Scope
