### ISSUE TITLE
Terminal opens extra tab on each start

### ISSUE THREAD

**Issue by ghabit** [elementary/terminal#452] opened 2020-01-08 17:33 UTC
Hello!
Every time i am opening Terminal it opens an extra tab. Looks like bug.
![Запись экрана от 2020-01-08 20 32 23](https://user-images.githubusercontent.com/70936/72001220-04f59100-3256-11ea-8926-d7e9aa81f2c6.gif)
Or maybe I can't find right option?
Thank you.

**Comment by jeremypw** [comment] 2020-01-08 17:48
Duplicate of #441.  A fix has just been merged into master source.

**Closed by jeremypw** 2020-01-08 17:48 UTC
Labels: Status: Duplicate
