### ISSUE TITLE
Split Layout within the same terminal window

### ISSUE THREAD

**Issue by NadavKeren** [elementary/terminal#621] opened 2021-09-08 15:58 UTC
## Problem
When needed to monitor multiple processes on the terminal, there is no option to create a split layout so one would be able to monitor several different tabs in the same terminal window. 
You can open several tabs in the same window, but as far as I can see, there is no option to put these tabs side by side **on the same window**, thus, you need to either:
1. Use multiple terminal windows.
2. Use multiplexer software such as TMux or Screen.

Some alternative terminal software allows splitting the window, so several independent tabs can be used, that includes Konsole and Terminator.

IMO it is a Quality-of-Life feature that can boost productivity using the terminal.

## Proposal
Add the ability to split the window horizontally/vertically, with additional sub-splits (that means, one can continue splitting the windows as he wishes). 

Another QOL feature (that I haven't seen yet) is being able to save layouts for quick reference (commonly used by the user; I tend to create the same layouts all the time, depends on what I wish to do).

### On konsole:
![konsole-version](https://user-images.githubusercontent.com/12783654/132543221-2cedfaeb-00bb-4596-89aa-ee3cac4d9b07.png)
### On Terminator:
![terminator-split-screen](https://user-images.githubusercontent.com/12783654/132542918-c0c644f9-1875-419d-9d72-b4ab9eab2ff9.png)

#### Another good reference (Vim):
![vim-split-tabs](https://user-images.githubusercontent.com/12783654/132542915-263f1ef9-befa-4096-8270-d0ea9b55df24.png)

**Thanks for the excellent terminal!** :1st_place_medal:

**Comment by jeremypw** [comment] 2021-09-08 16:51
The tendency has been for elementaryos to remove SplitWindow capability from apps like Code that used to have it so this might be a design conflict. As you say. for a power user, an alternative terminal app might be more suitable if you do not want to juggle multiple disconnected windows.  

Something that has been requested elsewhere, and may be implemented, is to restore *all* windows so you could set up a layout once and reuse it.

**Comment by danrabbit** [comment] 2021-09-08 18:29
Yup, this is a duplicate of #102 

Tiling is the responsibility of the window manager, so this is indeed a design conflict.

**Closed by danrabbit** 2021-09-08 18:29 UTC
