### ISSUE TITLE
Terminal always add a new Home tab on start

### ISSUE THREAD

**Issue by nnmlss** [elementary/terminal#444] opened 2020-01-04 11:42 UTC
## Prerequisites
- [+] I have searched open and closed issues for duplicates.

## Describe the bug
After the last update today the terminal application always opens a new Home tab on launch, no matter it is from slingshot menu or from a keyboard shortcut. Because I want to keep my tabs history at the end of session I have like 5 home tabs.

### Expected behavior
On launch of the application to not open a new home tab.

## Platform Information

![Screenshot from 2020-01-04 13 38 06](https://user-images.githubusercontent.com/1779227/71764983-83210300-2ef7-11ea-9412-76a9a3fec09a.png)

- [+] I'm using the latest released stable version

**Comment by jeremypw** [comment] 2020-01-04 17:03
What happens when you launch from Plank?  For me, the previous tabs are restored but a new Home tab is also added.  Note that Terminal now honors your privacy setting in Switchboard.  It must be "ON" for tabs to be restored.

**Comment by jeremypw** [comment] 2020-01-04 17:08
I think you are right though, that we do not want a new Home tab to added if tabs have been restored and that is a regression.

**Comment by jeremypw** [comment] 2020-01-04 18:48
I added a fix for this to an existing PR which was already touching the relevant code.

**Comment by nnmlss** [comment] 2020-01-04 20:49
Yes, I specially enabled the history On only because of that, no other settings there are active. Can I achieve your fix before the official update?

**Comment by jeremypw** [comment] 2020-01-05 13:09
You could use the "daily" repository to install the master version of terminal (https://launchpad.net/~elementary-os/+archive/ubuntu/daily) to get the fix once approved.  You could install the fix immediately by compiling it from source (with the usual caveats)

**Comment by janxkoci** [comment] 2020-01-05 14:19
FYI this started to happen after the last update (which I installed yesterday).

**Comment by alfianguide** [comment] 2020-01-08 06:09
I'm occured this after yesterday update.

**Comment by alfianguide** [comment] 2020-01-08 06:10
I think it's because history things update isn't it?

**Comment by alfianguide** [comment] 2020-01-08 06:11
• Don't remember tabs when History is disabled in System Settings

**Comment by nnmlss** [comment] 2020-01-08 11:02
Yes, it happens after the history update and **the developper already added a fix to that**, but it takes time until it is implemented. 
In order to value the developper's time you better read the posts above before posting comments and post comments only if you have to add something valuable for the process.

**Closed** 2020-01-08 15:55 UTC
