### ISSUE TITLE
System-wide Hot key to open/close the existing Terminal

### ISSUE THREAD

**Issue by TylerLeonhardt** [elementary/terminal#319] opened 2018-11-02 03:01 UTC
I like <kbd>super</kbd>+<kbd>T</kbd> but it always opens a _new_ terminal. What I'm looking for is some sort of keybinding that would open the _existing_ terminal that I have open.

Since Terminal has tabs, I find myself only using one window so a quick way to show/hide Terminal would be a great increase in my productivity. Without this, I might have to go look at other terminals. :cry:

**Comment by arshubham** [comment] 2018-11-02 06:18
Related Issue https://github.com/elementary/terminal/issues/53

**Comment by andreasfelix** [comment] 2019-07-06 14:44
I wrote a simple script which is able to focus an existing window. It depends on `xdotool` and `wmctrl`, which can be installed with:

```bash
apt install xdotool wmctrl
```
The script behaves in that way that if ..
- **Case 1**: ... the application is not running, it opens an new instance.
- **Case 2**: ... the application is running but is not focused, it focuses the instance with highest z-index.
- **Case 3**: ... the application is running and has focus, it focuses another instance (lowest z-index).

**Usage:**  To use this script to focus an existing terminal window go to *System Settings > Keyboard > Shortcuts > Custom Shortcut* and bind a custom shortcut to:
```
/path/to/script terminal io.elementary.terminal
```

Don't forget to make the scirpt executable before (`chmod +x script`). 

---

I personally have bound all my important applications (files, terminal, browser, ...) to a combination of **Super+Key**. Additionally I bound **Super+Shift+Key** to always open a new instance regardless if another instance is already running.

I wrote this script to demonstrate the imo extremely usefulness of the requested featured. I think especially the case-3-behavior is super convenient to quickly switch focus between two terminal windows. In case others find this useful too, this behavior cloud be directly implemented in gala ( which I think it handles global keyboard and should have all information about window position/z-index)?

I would also propose the same behavior for slingshot (#53):
- **Return** or **Click** would behave like the **cases 1-3** of the script. 
- **Shift-Return** or **middle/three-finger click** would always open a new instance. The **middle/three-finger click** would also be consistent with the current behavior of the dock.

---

**Script:**
To find out the **WM\_class** of an application use `xprop WM_CLASS | awk {'print $3'}` followed by a click on window.

```bash
# Usage: script ARG1 ARG2
#  ARG1: WM_CLASS of application
#  ARG2: /path/to/application
# Description: Use this script to create a keyboard shortcut to focus an application.
#  Case 1: application is not running           --> open an new instance
#  Case 2: application is running without focus --> focus instance with highest z-index
#  Case 3: application is running and has focus --> focus another instance (lowest z-index)

class_ids=$(xdotool search --onlyvisible --classname $1 | head -n "$(wmctrl -lx | awk '{ print $3 }' | grep $1 -c)")
if [ -z "$class_ids" ] ; then # case 1
    $2 &
else
    current_id=$(xdotool getactivewindow)
    if [ -z "$(echo $class_ids | grep $current_id)" ]; then # case 2
        new_id=$(echo $class_ids | awk '{ print $NF}')
    else # case 3
        new_id=$(echo $class_ids | awk '{ print $1}')
    fi
    xdotool windowactivate "$new_id"
fi

```
In case anyone is wondering, the expression `"$(wmctrl -lx | awk '{ print $3 }' | grep $1 -c)"` is needed  for some applications to filter out "ghost"-class-ids returned by `xdotool`.

**Comment by jeremypw** [comment] 2019-07-06 16:27
Would this be better reported under `https://github.com/elementary/switchboard-plug-keyboard` - this handles the setting of system-wide keyboard shortcuts?

**Comment by danrabbit** [comment] 2019-12-11 00:46
I'm gonna go ahead and close this as a duplicate of #53

**Closed by danrabbit** 2019-12-11 00:46 UTC
