### ISSUE TITLE
Split terminal

### ISSUE THREAD

**Issue by robsontenorio** [elementary/terminal#517] opened 2020-05-30 00:50 UTC
## Prerequisites
- [ x ] I have searched open and closed issues for duplicates.

## Feature

Split terminal would be a nice feature!

![image](https://user-images.githubusercontent.com/118955/83315449-6ebb0b00-a1f6-11ea-8c1c-9a8f00db1b07.png)

**Comment by danrabbit** [comment] 2020-05-31 21:27
Closing as a duplicate of #102

**Closed by danrabbit** 2020-05-31 21:27 UTC
